### ISSUE TITLE
改成不依赖quick的，难吗

### ISSUE THREAD

**Issue by zhaozhantao** [liangX-cn/csd2lua#1]
里面用到cocos的代码不太多吧，好像就有一个fileutil，我打算改成不依赖cocos的，只用lua原生的方法来做导出。不知道这样实现起来难不难

**Comment by liangX-cn** [comment]
设计初衷是尽量不导出冗余语句，所以采用了“创建真实 Cocos2d-x 对象，拿它的默认属性值来进行对比，以决定是否导出类似 setFlippedX(false) 这些语句”的方式。所以现在需要跑在 Cocos2d-x 环境下。

如果不想依赖 Cocos2d-x 库，去掉那些用于比较意图的代码就可。

**Comment by zhaozhantao** [comment]
嗯，谢谢解答，我想的是，把这个脚本，用来当打包脚本的一部分，自动执行。
